### PR TITLE
Add a button to tidy up captions

### PR DESCRIPTION
**Pull request by zixaphir**
Removes extra commas and spaces, and ensures every comma ends with a single space.

### CODE REVIEW

**Comment by tderkert** [comment]
Thanks for the pull request, and I really appreciate the effort to contribute to the project. I'm hoping you find the tool useful to some degree.

Sorry for the slow reaction to your PT. I checked tested your PR quickly. It cleaned up extra spaces and missing spaces, but It seems to add commas at the end of all captions which feels less clean. Any thoughts on that?

**Comment by tderkert** [comment]
Another thing that would be neat is having a tooltip on hover to explain what 'Tidy Caption' means, as it's not obvious exactly what it does before clicking it. The button component doesn't support that at the moment I think so might add that later. Feel free to add it if you feel like it.

**Comment by tderkert** [comment]
Removed the comma at the end and added some code to remove multiple spaces. Any objections?

**Comment by zixaphir** [comment]
I'm good with however you feel it should work. I only added the extra comma because it suited my use-case. I could add an option to do it if you want but either way, I just wanted to share something I found useful

**Comment by tderkert** [comment]
Personally think it looks tidier without the comma at the end. I guess training scripts have no problem ignoring it. I would rather have it as an option in the module in that case, similar to how it works in the Append script.

**Comment by tderkert** [comment]
Ill merge this fro now. Feel free to come with more suggestions and ideas. 🙏

**Pull request merged**
